/**
 * Conjugation Engine — runtime generator for Levantine Arabic verb conjugations.
 *
 * Single entry point: getConjugation(verb, tense, person)
 * - If verb.conjugations is not null → return from static JSON
 * - Otherwise → generate from root_letters + form template
 * - Cache generated conjugations in-memory on the verb object (RAM only)
 */

import { FORM_TEMPLATES, normalizeFormLabel, isRiskyForm } from './formTemplates.js';

/**
 * Get a specific conjugation form for a verb.
 *
 * @param {Object} verb - Verb object from verbs.json
 * @param {string} tense - 'perfect' | 'imperfect' | 'bi_imperfect' | 'imperative'
 * @param {string} person - 'ana' | 'nihna' | 'inta' | 'inti' | 'intu' | 'huwwe' | 'hiyye' | 'hinne'
 * @returns {{ person, arabic, translit, english } | null}
 */
export function getConjugation(verb, tense, person) {
  // Ensure conjugations are populated
  ensureConjugations(verb);

  const tenseData = verb.conjugations?.[tense];
  if (!tenseData?.forms) return null;

  return tenseData.forms.find(f => f.person === person) || null;
}

/**
 * Get all forms for a verb+tense.
 */
export function getTenseConjugations(verb, tense) {
  ensureConjugations(verb);
  return verb.conjugations?.[tense] || null;
}

/**
 * Ensure a verb's conjugations are populated.
 * If conjugations is null and we have root_letters + form, generate them.
 */
export function ensureConjugations(verb) {
  if (verb.conjugations !== null) return;
  if (!verb.root_letters || !verb.form) return;

  // Correctness gate (SAD §8.3): verbs whose form label carries an irregular/weak/
  // geminate qualifier are generated WRONG by the sound-root templates (the qualifier
  // is stripped). Withhold them — an empty paradigm is safer than a wrong one — until a
  // signed static table is authored. See isRiskyForm.
  if (isRiskyForm(verb.form)) return;

  const templateKey = normalizeFormLabel(verb.form);
  if (!templateKey) return;

  const templateFn = FORM_TEMPLATES[templateKey];
  if (!templateFn) return;

  const generated = templateFn(verb.root_letters);
  if (generated) {
    verb.conjugations = generated;
  }
}

/**
 * Check if a verb can have its conjugations generated by the engine.
 */
export function canGenerate(verb) {
  if (verb.conjugations !== null) return false; // Already has static
  if (!verb.root_letters || !verb.form) return false;
  if (isRiskyForm(verb.form)) return false; // withheld — would generate a wrong irregular form
  const templateKey = normalizeFormLabel(verb.form);
  return templateKey !== null && FORM_TEMPLATES[templateKey] !== undefined;
}
